### ISSUE TITLE
Method declaration incompatibility - morphTo, Laravel 5.6.18

### ISSUE THREAD

**Issue by dobrebydlo** [laravel-ardent/ardent#311]
PHP Warning:  Declaration of LaravelArdent\Ardent\Ardent::morphTo($name = NULL, $type = NULL, $id = NULL) should be compatible with Illuminate\Database\Eloquent\Model::morphTo($name = NULL, $type = NULL, $id = NULL, $ownerKey = NULL) in /.../vendor/laravelbook/ardent/src/Ardent/Ardent.php on line 25

**Comment by exupero** [comment]
I had to revert to Laravel 5.5.28 before this error disappeared, so it appears to be a problem with Laravel 5.6 in general.

**Comment by spyp** [comment]
its fixed right now with version 3.5
