### ISSUE TITLE
Laravel 5.7 Issue

### ISSUE THREAD

**Issue by lloricode** [laravel-ardent/ardent#312]
Hi!, after installing `laravelbook/ardent:dev-master` through composer, there is an issue

```php

In ArdentServiceProvider.php line 22:

  Call to undefined method LaravelArdent\Ardent\Providers\ArdentServiceProvid
  er::package()

```

**Comment by igorsantos07** [comment]
Would you try 3.4.* and see if it persists?
I'm thinking #305 included something that's not used anymore - the said service provider...

**Comment by lloricode** [comment]
@igorsantos07 thanks, it works now, but can we fix this to get the latest updates?

**Comment by lloricode** [comment]
we need this https://github.com/laravel-ardent/ardent/pull/310/files,

![screenshot from 2018-10-09 10-09-54](https://user-images.githubusercontent.com/8251344/46642791-80781680-cbab-11e8-8ecf-bef5a4609648.png)

**Comment by lloricode** [comment]
i think we need to have a new PR to fix this?

**Comment by igorsantos07** [comment]
@lloricode check 3.6.0. Hopefully, it'll solve the matter and not break the code, as I've removed two files without being able to test them. You tested one, the other was the Facade (which I'm pretty sure I never used), so we're good to go?

**Comment by lloricode** [comment]
@igorsantos07 thanks, i will check that :)
